---
name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency: tag-new-version-group

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: opensafely-core/research-action@v2

  tag-new-version:
    needs: [test-integration]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Tag new version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
